In [1]:
import pandas as pd
df = pd.read_excel("C:/Users/MML/Desktop/一/test.xlsx")
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,姓名,年龄,性别,焦虑得分,备注列1,备注列2
0,NaN,NaN,NaN,NaN,NaN,张三,18,男,85,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,李四,NaN,女,未知,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,王五,20,男,90,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,张三,18,男,85,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,赵六,19,NaN,80,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,小强,男,25,98,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,小美,19,女,75,NaN,NaN

In [5]:
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      7 non-null      str
 1   年龄      6 non-null      object
 2   性别      6 non-null      object
 3   焦虑得分    7 non-null      object
dtypes: object(3), str(1)
memory usage: 356.0+ bytes

   姓名   年龄   性别 焦虑得分
0  张三   18    男   85
1  李四  NaN    女   未知
2  王五   20    男   90
3  张三   18    男   85
4  赵六   19  NaN   80
5  小强    男   25   98
6  小美   19    女   75

In [6]:
df = df.dropna(axis=1,how='all')
df

   姓名   年龄   性别 焦虑得分
0  张三   18    男   85
1  李四  NaN    女   未知
2  王五   20    男   90
3  张三   18    男   85
4  赵六   19  NaN   80
5  小强    男   25   98
6  小美   19    女   75

In [8]:
df.rename(columns={"焦虑得分":"焦虑分数"},inplace=True)
df

   姓名   年龄   性别 焦虑分数
0  张三   18    男   85
1  李四  NaN    女   未知
2  王五   20    男   90
3  张三   18    男   85
4  赵六   19  NaN   80
5  小强    男   25   98
6  小美   19    女   75

In [9]:
df = df.drop_duplicates()
df

   姓名   年龄   性别 焦虑分数
0  张三   18    男   85
1  李四  NaN    女   未知
2  王五   20    男   90
4  赵六   19  NaN   80
5  小强    男   25   98
6  小美   19    女   75

In [11]:
df = df.replace("未知",89)
df

   姓名   年龄   性别 焦虑分数
0  张三   18    男   85
1  李四  NaN    女   89
2  王五   20    男   90
4  赵六   19  NaN   80
5  小强    男   25   98
6  小美   19    女   75

In [12]:
df.loc[5,"年龄"] = 19
df.loc[5,"性别"] = "男"
df

   姓名   年龄   性别 焦虑分数
0  张三   18    男   85
1  李四  NaN    女   89
2  王五   20    男   90
4  赵六   19  NaN   80
5  小强   19    男   98
6  小美   19    女   75

In [13]:
df = df.dropna()
df

   姓名  年龄 性别 焦虑分数
0  张三  18  男   85
2  王五  20  男   90
5  小强  19  男   98
6  小美  19  女   75

In [15]:
df["焦虑分数"] = df["焦虑分数"].astype(float)
df

   姓名  年龄 性别  焦虑分数
0  张三  18  男  85.0
2  王五  20  男  90.0
5  小强  19  男  98.0
6  小美  19  女  75.0

In [16]:
df.info()
df

<class 'pandas.DataFrame'>
Index: 4 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      4 non-null      str
 1   年龄      4 non-null      object
 2   性别      4 non-null      object
 3   焦虑分数    4 non-null      float64
dtypes: float64(1), object(2), str(1)
memory usage: 160.0+ bytes

   姓名  年龄 性别  焦虑分数
0  张三  18  男  85.0
2  王五  20  男  90.0
5  小强  19  男  98.0
6  小美  19  女  75.0

In [17]:
df.head()
df

   姓名  年龄 性别  焦虑分数
0  张三  18  男  85.0
2  王五  20  男  90.0
5  小强  19  男  98.0
6  小美  19  女  75.0

In [18]:
df.to_csv("C:/Users/MML/Desktop/一/我的数据.csv",index=False)

In [19]:
df = pd.read_excel("C:/Users/MML/Desktop/一/test2.xlsx")
df

    姓名  分数  状态      备注
0  张 三  85  及格     NaN
1  李 四  缺考  缺考  有特殊符号！
2   王五  90  优秀     NaN
3  赵 六  未知  及格   这里有空格
4   钱七  75  缺考     NaN

In [20]:
df["分数"] = df["分数"].replace(["缺考","未知"],0)
df

    姓名  分数  状态      备注
0  张 三  85  及格     NaN
1  李 四   0  缺考  有特殊符号！
2   王五  90  优秀     NaN
3  赵 六   0  及格   这里有空格
4   钱七  75  缺考     NaN

In [21]:
df["姓名"] = df["姓名"].str.replace(r"\s+","",regex=True)
df

   姓名  分数  状态      备注
0  张三  85  及格     NaN
1  李四   0  缺考  有特殊符号！
2  王五  90  优秀     NaN
3  赵六   0  及格   这里有空格
4  钱七  75  缺考     NaN

In [22]:
df["分数"] = df["分数"].astype(float)
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      5 non-null      str
 1   分数      5 non-null      float64
 2   状态      5 non-null      str
 3   备注      2 non-null      str
dtypes: float64(1), str(3)
memory usage: 292.0 bytes

   姓名    分数  状态      备注
0  张三  85.0  及格     NaN
1  李四   0.0  缺考  有特殊符号！
2  王五  90.0  优秀     NaN
3  赵六   0.0  及格   这里有空格
4  钱七  75.0  缺考     NaN

In [23]:
df = df.dropna()
df

   姓名   分数  状态      备注
1  李四  0.0  缺考  有特殊符号！
3  赵六  0.0  及格   这里有空格

In [ ]:
df.to_csv("C:/Users/MML/Desktop/一/我的数据.csv",