In [3]:
import pandas as pd
df = pd.read_excel("C:/Users/MML/Desktop/一/test1.xlsx")
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,姓名,年龄,性别,焦虑得分
0,NaN,NaN,NaN,NaN,NaN,小米,18,女,89
1,NaN,NaN,NaN,NaN,NaN,小李,NaN,男,87
2,NaN,NaN,NaN,NaN,NaN,王五,19,NaN,90
3,NaN,NaN,NaN,NaN,NaN,小镇,20,男,67
4,NaN,NaN,NaN,NaN,NaN,李四,19,男,未知
5,NaN,NaN,NaN,NaN,NaN,刘帅,21,女,78
6,NaN,NaN,NaN,NaN,NaN,小强,男,21,98
7,NaN,NaN,NaN,NaN,NaN,小米,18,女,89

In [5]:
df.isnull()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,姓名,年龄,性别,焦虑得分
0,True,True,True,True,True,False,False,False,False
1,True,True,True,True,True,False,True,False,False
2,True,True,True,True,True,False,False,True,False
3,True,True,True,True,True,False,False,False,False
4,True,True,True,True,True,False,False,False,False
5,True,True,True,True,True,False,False,False,False
6,True,True,True,True,True,False,False,False,False
7,True,True,True,True,True,False,False,False,False

In [6]:
df = df.dropna(axis=1,how='all')
df

   姓名   年龄   性别 焦虑得分
0  小米   18    女   89
1  小李  NaN    男   87
2  王五   19  NaN   90
3  小镇   20    男   67
4  李四   19    男   未知
5  刘帅   21    女   78
6  小强    男   21   98
7  小米   18    女   89

In [7]:
df = df.drop_duplicates()

In [8]:
df

   姓名   年龄   性别 焦虑得分
0  小米   18    女   89
1  小李  NaN    男   87
2  王五   19  NaN   90
3  小镇   20    男   67
4  李四   19    男   未知
5  刘帅   21    女   78
6  小强    男   21   98

In [9]:
df = df.replace("未知",78)
df

   姓名   年龄   性别 焦虑得分
0  小米   18    女   89
1  小李  NaN    男   87
2  王五   19  NaN   90
3  小镇   20    男   67
4  李四   19    男   78
5  刘帅   21    女   78
6  小强    男   21   98

In [10]:
df.loc[6,"年龄"] = 21
df.loc[6,"性别"] = "男"
df.loc[1,"年龄"] = 18
df.loc[2,"性别"] = "男"

In [11]:
df

   姓名  年龄 性别 焦虑得分
0  小米  18  女   89
1  小李  18  男   87
2  王五  19  男   90
3  小镇  20  男   67
4  李四  19  男   78
5  刘帅  21  女   78
6  小强  21  男   98

In [13]:
df.to_csv("C:/Users/MML/Desktop/一/我的数据.csv",index=False)